# test_station_3.py   combine ID & OD
# updated on 22_9_2025 (now also saves cam3_combined.bmp with both ID & OD)
from station_3 import main
import cv2

# Load test image
image_path = r"D:\PIM_15-09-25\Pravi_Flask\static\Cam1InputImages\cam3.bmp"
frame = cv2.imread(image_path)
print(f"DEBUG: Loaded image from: {image_path}")

# Identification
part = "SUPPORT PISTON"
subpart = "28.10.019"

# Contour area windows
min_id_area = "13000"
max_id_area = "23000"
min_od_area = "110000"
max_od_area = "160000"

# Shape filters (use "NA" to disable)
min_circularity = "0.50"
max_circularity = "1.15"
min_aspect_ratio = "0.30"
max_aspect_ratio = "1.10"

# Burr Detection Parameters (ID)
ID2_OFFSET_ID = "10"
HIGHLIGHT_SIZE_ID = "40"
ID_BURR_MIN_AREA = "60"
ID_BURR_MAX_AREA = "400"
ID_BURR_MIN_PERIMETER = "30"
ID_BURR_MAX_PERIMETER = "300"

# Burr Detection Parameters (OD)
ID2_OFFSET_OD = "10"
HIGHLIGHT_SIZE_OD = "40"
OD_BURR_MIN_AREA = "60"
OD_BURR_MAX_AREA = "400"
OD_BURR_MIN_PERIMETER = "30"
OD_BURR_MAX_PERIMETER = "300"

# Output folder
output_folder = r"output\output_image"

print("DEBUG: Parameters set for both ID and OD")

result = main(
    part, subpart, frame,
    # ID parameters
    ID2_OFFSET_ID, HIGHLIGHT_SIZE_ID,
    ID_BURR_MIN_AREA, ID_BURR_MAX_AREA, ID_BURR_MIN_PERIMETER, ID_BURR_MAX_PERIMETER,
    # OD parameters
    ID2_OFFSET_OD, HIGHLIGHT_SIZE_OD,
    OD_BURR_MIN_AREA, OD_BURR_MAX_AREA, OD_BURR_MIN_PERIMETER, OD_BURR_MAX_PERIMETER,
    # Contour selection
    min_id_area, max_id_area, min_od_area, max_od_area,
    min_circularity, max_circularity, min_aspect_ratio, max_aspect_ratio,
    output_folder
)

print("\n--- Final Returned Output ---")
print(result)









# # test_station_3.py   combine ID & OD  [web:2]
# # updated on 22_9_2025 (now also saves cam3_combined.bmp with both ID & OD)  [web:2]
# from station_3 import main
# import cv2

# # Load the test image from disk; imread returns a BGR image for downstream processing in OpenCV pipelines  [web:2]
# image_path = r"D:\PIM_15-09-25\Pravi_Flask\static\Cam1InputImages\cam3.bmp"
# frame = cv2.imread(image_path)
# print(f"DEBUG: Loaded image from: {image_path}")

# # Identify the part and subpart for logging and results labeling in outputs and return payloads  [web:2]
# part = "SUPPORT PISTON"
# subpart = "28.10.019"

# # Define ID contour area window (in pixels^2) to search for the inner ring; used to select the ID contour by size  [web:2]
# min_id_area = "13000"
# max_id_area = "23000"
# # Define OD contour area window (in pixels^2) to search for the outer ring; used to select the OD contour by size  [web:2]
# min_od_area = "110000"
# max_od_area = "160000"

# # Optional shape filters for contour selection; circularity and aspect ratio constrain candidate contours beyond area  [web:2]
# min_circularity = "0.50"
# max_circularity = "1.15"
# min_aspect_ratio = "0.30"
# max_aspect_ratio = "1.10"

# # Burr detection band and filtering for ID: offset builds the outward ring, highlight controls defect box size, area/perimeter filter burr blobs  [web:2]
# ID2_OFFSET_ID = "10"
# HIGHLIGHT_SIZE_ID = "40"
# ID_BURR_MIN_AREA = "60"
# ID_BURR_MAX_AREA = "400"
# ID_BURR_MIN_PERIMETER = "30"
# ID_BURR_MAX_PERIMETER = "300"

# # Burr detection band and filtering for OD: inward ring band from OD contour, same filters applied to small edge burr contours  [web:2]
# ID2_OFFSET_OD = "10"
# HIGHLIGHT_SIZE_OD = "40"
# OD_BURR_MIN_AREA = "60"
# OD_BURR_MAX_AREA = "400"
# OD_BURR_MIN_PERIMETER = "30"
# OD_BURR_MAX_PERIMETER = "300"

# # Output folder for saving individual ID/OD overlays and combined images generated by station_3  [web:2]
# output_folder = r"output\output_image"

# print("DEBUG: Parameters set for both ID and OD")

# # Invoke station_3 main with ID and OD burr parameters, contour selection windows, and filters; returns dict with statuses and saved paths  [web:2]
# result = main(
#     part, subpart, frame,
#     # ID parameters
#     ID2_OFFSET_ID, HIGHLIGHT_SIZE_ID,
#     ID_BURR_MIN_AREA, ID_BURR_MAX_AREA, ID_BURR_MIN_PERIMETER, ID_BURR_MAX_PERIMETER,
#     # OD parameters
#     ID2_OFFSET_OD, HIGHLIGHT_SIZE_OD,
#     OD_BURR_MIN_AREA, OD_BURR_MAX_AREA, OD_BURR_MIN_PERIMETER, OD_BURR_MAX_PERIMETER,
#     # Contour selection
#     min_id_area, max_id_area, min_od_area, max_od_area,
#     min_circularity, max_circularity, min_aspect_ratio, max_aspect_ratio,
#     output_folder
# )

# # Print the summarized return payload containing ID/OD burr result (OK/NOK), counts, and image paths (including combined overlays)  [web:2]
# print("\n--- Final Returned Output ---")
# print(result)
















# ## upto 23 sep_25  10am
# # test_station_3.py   combine ID & OD 
# # updated on 22_9_2025 (now also saves cam3_combined.bmp with both ID & OD)
# from station_3 import main
# import cv2

# # Load test image
# image_path = r"D:\PIM_15-09-25\Pravi_Flask\static\Cam1InputImages\cam3.bmp"
# frame = cv2.imread(image_path)
# print(f"DEBUG: Loaded image from: {image_path}")

# # Identification
# part = "SUPPORT PISTON"
# subpart = "28.10.019"

# # Contour area windows
# min_id_area = "13000"
# max_id_area = "23000"
# min_od_area = "110000"
# max_od_area = "160000"

# # Shape filters (use "NA" to disable)
# min_circularity = "0.50"
# max_circularity = "1.15"
# min_aspect_ratio = "0.30"
# max_aspect_ratio = "1.10"

# # Burr Detection Parameters (ID)
# ID2_OFFSET_ID = "10"
# HIGHLIGHT_SIZE_ID = "40"
# ID_BURR_MIN_AREA = "60"
# ID_BURR_MAX_AREA = "400"
# ID_BURR_MIN_PERIMETER = "30"
# ID_BURR_MAX_PERIMETER = "300"

# # Burr Detection Parameters (OD)
# ID2_OFFSET_OD = "10"
# HIGHLIGHT_SIZE_OD = "40"
# OD_BURR_MIN_AREA = "60"
# OD_BURR_MAX_AREA = "400"
# OD_BURR_MIN_PERIMETER = "30"
# OD_BURR_MAX_PERIMETER = "300"

# # Output folder
# output_folder = r"output\output_image"

# print("DEBUG: Parameters set for both ID and OD")

# result = main(
#     part, subpart, frame,
#     # ID parameters
#     ID2_OFFSET_ID, HIGHLIGHT_SIZE_ID,
#     ID_BURR_MIN_AREA, ID_BURR_MAX_AREA, ID_BURR_MIN_PERIMETER, ID_BURR_MAX_PERIMETER,
#     # OD parameters
#     ID2_OFFSET_OD, HIGHLIGHT_SIZE_OD,
#     OD_BURR_MIN_AREA, OD_BURR_MAX_AREA, OD_BURR_MIN_PERIMETER, OD_BURR_MAX_PERIMETER,
#     # Contour selection
#     min_id_area, max_id_area, min_od_area, max_od_area,
#     min_circularity, max_circularity, min_aspect_ratio, max_aspect_ratio,
#     output_folder
# )

# print("\n--- Final Returned Output ---")
# print(result)

































# # updated on 20_9_2025 (adds circularity/aspect ratio controls)
# # Test file example usage for station 3
# from station_3 import main
# import cv2

# # Load test image
# image_path = r"D:\PIM_15-09-25\Pravi_Flask\static\Cam1InputImages\cam3.bmp"
# frame = cv2.imread(image_path)
# print(f"DEBUG: Loaded image from: {image_path}")

# # ==== Configurable Parameters for Station 3 ====
# part = "SUPPORT PISTON"
# subpart = "28.10.019"

# # ID/OD Contour Area Parameters
# min_id_area = "13000"
# max_id_area = "23000"
# min_od_area = "110000"
# max_od_area = "160000"

# # NEW: Shape filters for circular selection (use "NA" to disable)
# min_circularity = "0.50"   # 4*pi*A/P^2 lower bound (close to 1 for circles)
# max_circularity = "1.15"   # 4*pi*A/P^2 upper bound
# min_aspect_ratio = "0.30"  # w/h lower bound (≈1 for circles)
# max_aspect_ratio = "1.10"  # w/h upper bound


# # Burr Detection Parameters
# ID2_OFFSET = "10"
# HIGHLIGHT_SIZE = "40"
# id_BURR_MIN_AREA = "60"
# id_BURR_MAX_AREA = "400"
# id_BURR_MIN_PERIMETER = "30"
# id_BURR_MAX_PERIMETER = "300"

# # Output folder
# output_folder = r"output\output_image"

# print("DEBUG: Station 3 - All parameters configured:")
# print(f"- ID Area Range: {min_id_area} - {max_id_area}")
# print(f"- OD Area Range: {min_od_area} - {max_od_area}")
# print(f"- Circularity: {min_circularity} - {max_circularity}")
# print(f"- Aspect Ratio: {min_aspect_ratio} - {max_aspect_ratio}")
# print(f"- Burr Area Range: {id_BURR_MIN_AREA} - {id_BURR_MAX_AREA}")
# print(f"- Burr Perimeter Range: {id_BURR_MIN_PERIMETER} - {id_BURR_MAX_PERIMETER}")
# print(f"- ID2 Offset: {ID2_OFFSET}, Highlight Size: {HIGHLIGHT_SIZE}")

# # ==== Call the main() function with all parameters ====
# result = main(
#     part, subpart, frame,
#     ID2_OFFSET, HIGHLIGHT_SIZE,
#     id_BURR_MIN_AREA, id_BURR_MAX_AREA,
#     id_BURR_MIN_PERIMETER, id_BURR_MAX_PERIMETER,
#     min_id_area, max_id_area,
#     min_od_area, max_od_area,
#     # NEW: pass shape filters
#     min_circularity, max_circularity, min_aspect_ratio, max_aspect_ratio,
#     output_folder
# )

# # ==== Output ====
# print("\n--- Final Returned Output ---")
# print(result)
























# # updated on 14_9_2025
# # Test file example usage for station 3


# from station_3 import main
# import cv2

# # Load test image
# image_path = r"D:\Pravi\burr_images\new_glass\parts\19_9_25\support_piston\16.06.012\image0000376.bmp"
# frame = cv2.imread(image_path)
# print(f"DEBUG: Loaded image from: {image_path}")

# # ==== Configurable Parameters for Station 3 ====
# part = "SUPPORT PISTON"
# subpart = "16.06.012"

# # ID/OD Contour Area Parameters (NEW - Easy to modify from test file)
# min_id_area = "3000"      # Minimum area for ID contour detection
# max_id_area = "7000"      # Maximum area for ID contour detection
# min_od_area = "25000 "     # Minimum area for OD contour detection  
# max_od_area = "45000 "     # Maximum area for OD contour detection

# # Burr Detection Parameters
# ID2_OFFSET = "10"                    # Offset for ID2 ring creation
# HIGHLIGHT_SIZE = "40"                # Size of highlight rectangles around burrs
# id_BURR_MIN_AREA = "60"             # Minimum area for burr classification
# id_BURR_MAX_AREA = "400"            # Maximum area for burr classification
# id_BURR_MIN_PERIMETER = "30"        # Minimum perimeter for burr classification
# id_BURR_MAX_PERIMETER = "300"       # Maximum perimeter for burr classification

# # Output folder
# output_folder = r"output\output_image"

# print("DEBUG: Station 3 - All parameters configured:")
# print(f"- ID Area Range: {min_id_area} - {max_id_area}")
# print(f"- OD Area Range: {min_od_area} - {max_od_area}")
# print(f"- Burr Area Range: {id_BURR_MIN_AREA} - {id_BURR_MAX_AREA}")
# print(f"- Burr Perimeter Range: {id_BURR_MIN_PERIMETER} - {id_BURR_MAX_PERIMETER}")
# print(f"- ID2 Offset: {ID2_OFFSET}, Highlight Size: {HIGHLIGHT_SIZE}")

# # ==== Call the main() function with all parameters ====
# result = main(
#     part, subpart, frame,
#     ID2_OFFSET, HIGHLIGHT_SIZE, 
#     id_BURR_MIN_AREA, id_BURR_MAX_AREA, 
#     id_BURR_MIN_PERIMETER, id_BURR_MAX_PERIMETER,
#     min_id_area, max_id_area, 
#     min_od_area, max_od_area,
#     output_folder
# )

# # ==== Output ====
# print("\n--- Final Returned Output ---")
# print(result)













# # # # old 13_9_2025

# from station_3 import main
# import cv2

# # Load test image
# image_path = r"D:\Pravi\burr_images\new_glass\station1\dataset\19_9_25\VCXG.2-32C\image0000364.bmp"
# frame = cv2.imread(image_path)
# print(f"DEBUG: Loaded image from: {image_path}")  # Debug: Image loading confirmation

# # ==== Parameters ====  # Parameters passed as strings as in production environment
# part = "SUPPORT PISTON"
# subpart = "28.10.019"
# ID2_OFFSET = "10"
# HIGHLIGHT_SIZE = "40"
# id_BURR_MIN_AREA = "60"
# id_BURR_MAX_AREA = "400"
# id_BURR_MIN_PERIMETER = "30"
# id_BURR_MAX_PERIMETER = "300"
# output_folder = r"output\\output_image"

# print("DEBUG: Parameters set:", part, subpart, ID2_OFFSET, HIGHLIGHT_SIZE, id_BURR_MIN_AREA, id_BURR_MAX_AREA, id_BURR_MIN_PERIMETER, id_BURR_MAX_PERIMETER)  # Debug: Parameter confirmation

# # ==== Call the main() function from station_4 ====
# result = main(
#     part, subpart, frame,
#     ID2_OFFSET, HIGHLIGHT_SIZE, id_BURR_MIN_AREA,
#     id_BURR_MAX_AREA, id_BURR_MIN_PERIMETER, id_BURR_MAX_PERIMETER,
#     output_folder
# )

# # ==== Output ====
# print("\n--- Final Returned Output ---")
# print(result)
